CAPS_WORD_ENABLE = yes

# Small image
LTO_ENABLE = yes

MOUSEKEY_ENABLE = no
# CONSOLE_ENABLE = no
# COMMAND_ENABLE = no
# EXTRAKEY_ENABLE = no

# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = no
# MAGIC_ENABLE = no
